environment:
  global:
    MINGW_32: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32
    MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64
    TWINE_USERNAME:
      secure: 1Szp1iLA7WGoWd1p27WL8A==
    TWINE_PASSWORD:
      secure: R/khkrD1Q53akIsKedjTXQ==
    TWINE_REPOSITORY: https://test.pypi.org/legacy/

  matrix:
    - PYTHON: C:\Python35
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 32

    - PYTHON: C:\Python36
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 32

    - PYTHON: C:\Python37
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 32

    - PYTHON: C:\Python35-x64
      PYTHON_VERSION: 3.5
      PYTHON_ARCH: 64

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6
      PYTHON_ARCH: 64

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7
      PYTHON_ARCH: 64

platform:
  - x64
  - x86

install:
  #- appveyor DownloadFile https://raw.githubusercontent.com/horta/zlib.install/master/install.bat
  #- install.bat
  #- appveyor DownloadFile https://www.sqlite.org/2019/sqlite-amalgamation-3280000.zip
  #- 7z e sqlite-amalgamation-3280000.zip -oc:\sqlite
  #- SET INCLUDE=%programfiles%\zlib\include;c:\sqlite;%INCLUDE%
  #- SET INCLUDE=%INCLUDE%
  #- dir C:\mingw-w64
  #- vcpkg install zlib:"%platform%"-windows
  #- vcpkg install sqlite3:"%platform%"-windows
  #- SET INCLUDE=C:\Tools\vcpkg\packages\zlib_%platform%-windows\include;%INCLUDE%
  #- SET INCLUDE=C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\include;%INCLUDE%
  #- SET LIB=C:\Tools\vcpkg\packages\zlib_%platform%-windows\lib;%LIB%
  #- SET LIB=C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\lib;%LIB%
  #- SET PATH=C:\Tools\vcpkg\packages\zlib_%platform%-windows\bin;%PATH%
  #- SET PATH=C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\bin;%PATH%
  #- pip install -U cibuildwheel
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - if [%PYTHON_ARCH%] == [32] SET PATH=%MINGW_32%\bin;%PATH%
  - if [%PYTHON_ARCH%] == [64] SET PATH=%MINGW_64%\bin;%PATH%
  - COPY %MINGW_32%\opt\include\sqlite3.h %MINGW_32%\i686-w64-mingw32\include\sqlite3.h
  - COPY %MINGW_32%\opt\lib\libsqlite3.dll.a %MINGW_32%\i686-w64-mingw32\lib\libsqlite3.dll.a
  - COPY %MINGW_64%\opt\include\sqlite3.h %MINGW_64%\x86_64-w64-mingw32\include\sqlite3.h
  - COPY %MINGW_64%\opt\lib\libsqlite3.dll.a %MINGW_64%\x86_64-w64-mingw32\lib\libsqlite3.dll.a
  - gendef %PYTHON%\vcruntime140.dll
  - dlltool -D %PYTHON%\vcruntime140.dll -d vcruntime140.def -l %PYTHON%\libs\libvcruntime140.a
  - python -m pip install -U pip setuptools wheel
  - python ci\fix_compiler_error.py %PYTHON%

build_script:
  #- cibuildwheel --output-dir wheelhouse
  - python setup.py build -c mingw32
  - pip wheel -v -w wheelhouse .

before_deploy:
  - pip install -U twine

after_deploy:
  - >
    IF "%APPVEYOR_REPO_BRANCH%" == "master"
    (
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    twine upload "wheelhouse\\*whl" --skip-existing
    )
    )

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels