os: Visual Studio 2015

environment:
  global:
    #MINGW_32: C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32
    #MINGW_64: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
    BUILD_DEPENDS: "zlib sqlite"
    TWINE_REPOSITORY: pypi
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

  matrix:
    #- PYTHON: C:\Python35
    #  PYTHON_VERSION: 3.5
    #  PYTHON_ARCH: 32

    #- PYTHON: C:\Python36
    #  PYTHON_VERSION: 3.6
    #  PYTHON_ARCH: 32

    #- PYTHON: C:\Python37
    #  PYTHON_VERSION: 3.7
    #  PYTHON_ARCH: 32

    #- PYTHON: C:\Python38
    #  PYTHON_VERSION: 3.8
    #  PYTHON_ARCH: 32

    #- PYTHON: C:\Python35-x64
    #  PYTHON_VERSION: 3.5
    #  PYTHON_ARCH: 64

    #- PYTHON: C:\Python36-x64
    #  PYTHON_VERSION: 3.6
    #  PYTHON_ARCH: 64

    #- PYTHON: C:\Python37-x64
    #  PYTHON_VERSION: 3.7
    #  PYTHON_ARCH: 64

    #- PYTHON: C:\Python38-x64
    #  PYTHON_VERSION: 3.8
    #  PYTHON_ARCH: 64

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PYTHON%\Library\bin;%PATH%
  - conda info
  - python --version

build_script:
  - conda install --yes %BUILD_DEPENDS% conda-build
  - conda create --yes -n build_env python=%PYTHON_VERSION% %BUILD_DEPENDS%
  - CALL conda.bat activate build_env
  - conda update --yes setuptools pip
  - conda install --yes twine
  - set ZLIB_HOME=%PYTHON%\\Library
  - dir %ZLIB_HOME%\\include
  - dir %ZLIB_HOME%\\lib
  - python setup.py build_ext --inplace

artifacts:
  #- path: "wheelhouse\\*.whl"
  - path: "pyfastx*.pyd"
    name: Wheels