environment:
  global:
    CIBW_SKIP: cp27-* cp33-* cp34-*

platform:
  - x64
  - x86

cache:
  - C:\tools\vcpkg\installed

install:
  #- appveyor DownloadFile https://raw.githubusercontent.com/horta/zlib.install/master/install.bat
  #- install.bat
  #- appveyor DownloadFile https://www.sqlite.org/2019/sqlite-amalgamation-3280000.zip
  #- 7z e sqlite-amalgamation-3280000.zip -oc:\sqlite
  #- SET INCLUDE=%programfiles%\zlib\include;c:\sqlite;%INCLUDE%
  #- SET INCLUDE=%INCLUDE%
  - vcpkg install zlib:"%platform%"-windows
  - vcpkg install sqlite3:"%platform%"-windows
  - SET INCLUDE=C:\Tools\vcpkg\packages\zlib_%platform%-windows\include;%INCLUDE%
  - SET INCLUDE=C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\include;%INCLUDE%
  - SET LIB=C:\Tools\vcpkg\packages\zlib_%platform%-windows\lib;%LIB%
  - SET LIB=C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\lib;%LIB%
  - SET LIBPATH=C:\Tools\vcpkg\packages\zlib_%platform%-windows\lib;%LIBPATH%
  - SET LIBPATH=C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\lib;%LIBPATH%
  - dir C:\Tools\vcpkg\packages\sqlite3_%platform%-windows
  - dir C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\lib
  - dir C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\include
  - dir C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\bin
  - dir C:\Tools\vcpkg\packages\sqlite3_%platform%-windows\share\sqlite3
  - pip install -U cibuildwheel

build_script:
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels