environment:
  global:
    CIBW_SKIP: cp27-* cp33-* cp34-*
    CIBW_BEFORE_BUILD_WINDOWS: 

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/horta/zlib.install/master/install.bat
  - install.bat
  - SET INCLUDE=%programfiles%\zlib\include\zlib.h;%INCLUDE%
  - cmd: pip install -U cibuildwheel

build_script:
  - cmd: cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels