environment:
  global:
    MINGW_32: C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32
    MINGW_64: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64
    TWINE_REPOSITORY: pypi
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

matrix:
  fast_finish: false

install:
  - appveyor DownloadFile https://github.com/lmdu/mingw64/raw/master/i686-8.1.0-release-posix-dwarf-rt_v6-rev0.7z -FileName mw32.7z
  - 7z x -oC:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0 mw32.7z > NUL
  - if [%PYTHON_ARCH%] == [32] SET PATH=%MINGW_32%\bin;%PATH%
  - if [%PYTHON_ARCH%] == [64] SET PATH=%MINGW_64%\bin;%PATH%
  - COPY %MINGW_32%\opt\include\sqlite3.h %MINGW_32%\i686-w64-mingw32\include\sqlite3.h
  - COPY %MINGW_32%\opt\lib\libsqlite3.a %MINGW_32%\i686-w64-mingw32\lib\libsqlite3.a
  - COPY %MINGW_64%\opt\include\sqlite3.h %MINGW_64%\x86_64-w64-mingw32\include\sqlite3.h
  - COPY %MINGW_64%\opt\lib\libsqlite3.a %MINGW_64%\x86_64-w64-mingw32\lib\libsqlite3.a
  - COPY ci\distutils.cfg C:\Python27\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python34\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python35\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python36\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python37\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python27-x64\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python34-x64\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python35-x64\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python36-x64\Lib\distutils\distutils.cfg
  - COPY ci\distutils.cfg C:\Python37-x64\Lib\distutils\distutils.cfg
  - python -m pip install -U pip setuptools wheel
  #- python ci\fix_compiler_error.py %PYTHON%
  - pip install -U twine

build_script:
  - pip install -U cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  #- python setup.py build -c mingw32
  #- pip wheel -v -w wheelhouse .
  - IF "%APPVEYOR_REPO_TAG%" == "true" (twine upload --skip-existing wheelhouse/*.whl)

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels