language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - PIP=pip3

matrix:
  include:
    - sudo: required
      services:
        - docker

    - os: osx
      language: generic

before_install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew install zlib;
    fi
  - if [ "${TRAVIS_OS_NAME:-}" -ne "osx" ]; then
      yum install -y zlib-devel;
    fi

install:
  - $PIP install -U setuptools
  - $PIP install -U cibuildwheel
  - cibuildwheel --output-dir wheelhouse

script:
  - ls wheelhouse