language: python

env:
  global:
    #- CIBW_SKIP=""
    - CIBW_BEFORE_BUILD_LINUX="yum install -y zlib-devel sqlite-devel"
    - CIBW_BEFORE_BUILD_MACOS="brew install zlib sqlite3"
    - PIP=pip3
    - TWINE_REPOSITORY=pypi
    - TWINE_REPOSITORY_URL=https://upload.pypi.org/legacy/
    - CPPFLAGS=--coverage

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      git -C "$(brew --repo)" remote set-url origin https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git;
    fi
  - $PIP install cpp-coveralls
  - $PIP install pyfaidx

install:
  - $PIP install -U setuptools
  - $PIP install -U cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - python3 setup.py sdist --dist-dir wheelhouse

script:
  - ls wheelhouse
  - if [ "$TRAVIS_TAG" != "" ]; then
      python -m pip install -U twine;
      python -m twine upload --skip-existing wheelhouse/*;
    fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      python setup.py test;
    fi

after_success:
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then
      bash <(curl -s https://codecov.io/bash);
      coveralls --build-root .;
    fi
