language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - PIP=pip3

matrix:
  include:
    - sudo: required
      services:
        - docker
      before_install:
        - apt install -y zlib-dev

    - os: osx
      language: generic
      before_install:
        - brew install zlib

install:
  - $PIP install -U setuptools
  - $PIP install -U cibuildwheel
  - cibuildwheel --output-dir wheelhouse

script:
  - ls wheelhouse