language: python

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-*"
    - CIBW_BEFORE_BUILD_LINUX="yum install -y zlib-devel"
    - CIBW_BEFORE_BUILD_MACOS="brew install zlib"
    - PIP=pip3
    - TWINE_REPOSITORY=pypi
    - TWINE_REPOSITORY_URL=https://test.pypi.org/legacy/

matrix:
  include:
    - sudo: required
      services:
        - docker
    - os: osx
      language: generic

install:
  - $PIP install -U setuptools
  - $PIP install -U cibuildwheel
  - cibuildwheel --output-dir wheelhouse

script:
  - ls wheelhouse
  - if [ "$TRAVIS_TAG" != "" ]; then
      python -m pip install -U twine;
      python -m twine upload --skip-existing wheelhouse/*;
    fi

deploy:
  provider: pypi
  user: lmdu
  server: https://test.pypi.org/legacy/
  password:
     secure: ICuoaaUuYshqmfDJjBq6wG98Vo5PiunoAQCXgbyqeXisSM41/0O1on+s+8UDb01pXfoOB3pfDj1TTm7ieh381onV+1nFZjuT7fCt2ePUw2ACFpq0XYZX3gW2Kc8gC3sNy4juDj3TFNbgNJnq+UZX3Ix8N86OlTIdJhPGAQgarOPlD2/c/BVwwELDbC3MGV6hseVPAh8ICrMvhUUhKAHhaUEYrtunlzqV9Y/Ig/Qu7vS8CnNiU7lHd2jYEaFw5hPOyzoPEvsmX9B6jlx6D6lJwXN2lkeSwVMWu4s7HT78+meG5iGLPAKL46laTEyxRpotzwhI9sRKNR2EENIUZ48uowckXpxmpeHDF7el91QkaoGH/HT//J/an5xZPaXJLT8iM9u7gCz7/+yU5Zq38VSxrbOTBXRAB8Kv21d3wnNbsB6oNTUaKCngb3gCznD910XlNns1gKbVhBkUru0rU6LEvY3JLC53BURQkEFlkXZJ7TP/oQVFUEucXgxVDYI6GJQK79mz2/I4WdMzpBCBqpugyYdgWjqTez2MlQs4DomezZQkes/bS3JPAXp/COtmHORILD/rWp/hv7zqqxCKrQisd++O1uPxkhWQ42gfah+7Pc0fxbX/Git5ZYCf58Tz4MojZCFwCMEZ4V30syYrklqo0U8QOINBgh7COpZtjZgJMHQ=
  skip_cleanup: true
  skip_existing: true
  on:
    branch: master
    tags: true
