language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - yum install -y zlib-devel
  - $PIP install -U cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
