name: CodeCov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.8'

    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          pip install pyfaidx==0.5.8
          python setup.py test
        env:
          CPPFLAGS: -coverage
      - name: Upload Coverage to CodeCov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
